cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: petbox-images

server:
  port: 8080

  spring:
    http:
      multipart:
        max-file-size: 500MB
        max-request-size: 900MB