-- CREATE TABLE pets (
--     id UUID NOT NULL PRIMARY KEY ,
--     title VARCHAR(100),
--     author VARCHAR(100)
-- );
--
-- CREATE TABLE courses (
--                         id UUID NOT NULL PRIMARY KEY ,
--                         title VARCHAR(100),
--                         author VARCHAR(100),
--                         topic_id UUID NOT NULL,
--                         FOREIGN KEY(topic_id)
--                             REFERENCES pets(id)
-- );
--
-- CREATE TABLE lessons (
--                         id UUID NOT NULL PRIMARY KEY ,
--                         title VARCHAR(100),
--                         author VARCHAR(100),
--                         topic_id UUID NOT NULL ,
--                         course_id UUID NOT NULL ,
--                         FOREIGN KEY (topic_id)
--                             REFERENCES pets(id),
--                         FOREIGN KEY (course_id)
--                             REFERENCES courses(id)
-- );
